name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published
      - prereleased

jobs:
  build_source:
    name: Build tarball for source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run container build
        run: ./get_sources.sh
      - uses: actions/upload-artifact@v2
        with:
          path: install.tar.gz
          name: tarball

  build_installer:
    needs:
      - build_source
    name: Build .msix installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/download-artifact@v2
        with:
          path: .
          name: tarball
      - name: Run build
        run: |
          Import-Certificate -filepath .\DistroLauncher-Appx\SelfSigningCertificate.cer -certStorelocation cert:\currentuser\my
          .\build.bat
      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: x64/Debug/DistroLauncher-Appx/*.appx
      - if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: DistroLauncher-Appx/SelfSigningCertificate.cer,x64/Debug/DistroLauncher-Appx/DistroLauncher-Appx*Debug.appx
          allowUpdates: true
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
